<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-QA2UGQA" failures="0" tests="4" name="testCases.OpenSalesAppTestCase001" time="87.757" errors="1" timestamp="2022-03-15T08:44:59 IST" skipped="3">
  <testcase classname="testCases.OpenSalesAppTestCase001" name="loginTestCase" time="0.039">
    <skipped/>
  </testcase> <!-- loginTestCase -->
  <system-out/>
  <testcase classname="testCases.OpenSalesAppTestCase001" name="loginTestCase" time="0.110">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at org.openqa.selenium.support.ui.ExpectedConditions.elementIfVisible(ExpectedConditions.java:307)
at org.openqa.selenium.support.ui.ExpectedConditions.access$000(ExpectedConditions.java:40)
at org.openqa.selenium.support.ui.ExpectedConditions$10.apply(ExpectedConditions.java:293)
at org.openqa.selenium.support.ui.ExpectedConditions$10.apply(ExpectedConditions.java:290)
at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:208)
at uiServices.IPageActionsImp.verifyElementText(IPageActionsImp.java:155)
at pages.SalesAppHomePage.verify_SalesApp_Landing_Page(SalesAppHomePage.java:18)
at testCases.OpenSalesAppTestCase001.loginTestCase(OpenSalesAppTestCase001.java:34)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </error>
  </testcase> <!-- loginTestCase -->
  <system-out/>
  <testcase classname="testCases.OpenSalesAppTestCase001" name="loginTestCase" time="86.558">
    <skipped/>
  </testcase> <!-- loginTestCase -->
  <system-out/>
  <testcase classname="testCases.OpenSalesAppTestCase001" name="loginTestCase" time="1.050">
    <skipped/>
  </testcase> <!-- loginTestCase -->
  <system-out/>
</testsuite> <!-- testCases.OpenSalesAppTestCase001 -->
